spring:
  r2dbc:
    url: ${R2DBC_URL:r2dbc:mariadb://localhost:3306/template_db}
    username: ${R2DBC_ID:root}
    password: ${R2DBC_PW}

logging.level.org:
  springframework.r2dbc.core.DefaultDatabaseClient: debug